server:
  port: 7079
spring:
  application:
    name: feign-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    hostname:feign
ribbon:
  eureka:
    enabled: true
    